name: CI/CD to Railway

on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod tidy

      - name: Build Go app
        run: go build -o app .

      - name: Test
        run: go test ./... -v
