name: Deploy to VPS

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 72.62.124.125
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Spatium-Backend
            git pull origin deployment
            /usr/local/go/bin/go build -o app
            pkill app || true
            nohup ./app > app.log 2>&1 &
